# Generated by Django 4.1 on 2022-08-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pedido_cliente_alter_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
