# Generated by Django 4.1 on 2022-08-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
